title: Original Abstract Art by Jatin Aythora
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.25
  brandStrength: 0.3100359
  lightness: 0.6875
  brandColors:
    - '#ffffff'
    - '#000508'
    - '#9f9f9f'
    - '#005c00'
    - '#a5361a'
  rhythmicContrast: 0.25
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: Jatin Aythora Abtract Art
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.53698
layout_spectrum: 0.6989247
