name: Jatin Aythora Abtract Art
favicon: null
layout_spectrum: 1
typography_spectrum: 0.53698
title: Original Abstract Art by Jatin Aythora
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000508'
    - '#9f9f9f'
    - '#005c00'
    - '#a5361a'
  brandStrength: 0.1875
  lightness: 0.6875
  saturation: 0.625
  rhythmicContrast: 0.75
purpose: []
