name: Jatin Aythora Abtract Art
favicon: null
layout_spectrum: 0.7888238991145045
typography_spectrum: 0.5369808254763484
title: Original Contemporary and Abstract Art
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.2525004504714161
  lightness: 0.249528166372329
  saturation: 0.6312813593540341
  rhythmicContrast: 0.6517590484581888
purpose: []
