name: Jatin Aythora Abtract Art
favicon: null
layout_spectrum: 0.76962
typography_spectrum: 0.53698
title: Original Contemporary and Abstract Art
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#242c31'
    - '#9a9da0'
    - '#51575b'
    - '#c1c3c4'
  brandStrength: 0.625
  lightness: 0.625
  saturation: 0.625
  rhythmicContrast: 0.75
purpose: []
